# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cities_light.city',),
        ),
    ]
