# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 20:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import iampacks.agencia.agencia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccion', '__first__'),
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('perfil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telefono', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('activa', models.BooleanField(default=True, help_text='Só debería ter uma unica agencia ativa', verbose_name='Ativa')),
                ('logo', models.ImageField(blank=True, help_text='Logo a ser visualizado no site da agencia', null=True, upload_to='agencias/logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, help_text='Imagem com extenção ico de 48x48 pixels', null=True, upload_to='agencias/logos/', verbose_name='Favicon')),
                ('titulo_home', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo pagina inicial')),
                ('presentacion_home', models.TextField(blank=True, null=True, verbose_name='Presentação pagina inicial')),
                ('mapa_contacto', models.TextField(blank=True, help_text='Aqui tem que colar o HTML gerado no google maps a partir de seu endereço', null=True, verbose_name='Mapa pagina contato')),
                ('foto_agenciado_obligatoria', models.BooleanField(default=True, verbose_name='Foto Agenciado Obligatoria')),
            ],
            options={
                'verbose_name_plural': 'Agencias',
                'verbose_name': 'Agencia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Agenciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, null=True, verbose_name='e-mail')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nome')),
                ('apellido', models.CharField(max_length=60, verbose_name='Sobrenome')),
                ('fecha_nacimiento', models.DateField(validators=[iampacks.agencia.agencia.models.validate_fecha_nacimiento], verbose_name='Data nascimento')),
                ('nombre_artistico', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre artístico')),
                ('documento_rg', models.CharField(max_length=60, verbose_name='RG')),
                ('documento_cpf', models.CharField(blank=True, max_length=60, null=True, verbose_name='CPF')),
                ('documento_drt', models.CharField(blank=True, max_length=60, null=True, verbose_name='DRT')),
                ('responsable', models.CharField(blank=True, max_length=60, verbose_name='Responsabel')),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=100, verbose_name='Conta bancaria')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('altura', models.FloatField(validators=[iampacks.agencia.agencia.models.validate_altura], verbose_name='Altura (cm)')),
                ('peso', models.FloatField(verbose_name='Peso (kg)')),
                ('talle_camisa', models.IntegerField(verbose_name='Camisa')),
                ('talle_pantalon', models.IntegerField(verbose_name='Calça')),
                ('calzado', models.IntegerField(verbose_name='Calçado')),
                ('indicador_maneja', models.BooleanField(verbose_name='Dirige')),
                ('indicador_tiene_registro', models.BooleanField(verbose_name='Habilitação')),
                ('trabaja_como_extra', models.BooleanField(verbose_name='Faz figuração')),
                ('como_nos_conocio', models.TextField(blank=True, verbose_name='Como nos conheceu')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaçoes')),
                ('activo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('fecha_ingreso', models.DateField(default=datetime.datetime(2016, 3, 6, 20, 34, 42, 479546, tzinfo=utc), verbose_name='Data de agenciamento')),
                ('recurso_id', models.IntegerField(editable=False, null=True)),
                ('nombre_completo', models.CharField(editable=False, max_length=121)),
                ('danzas', models.ManyToManyField(blank=True, to='perfil.Danza', verbose_name='Danças')),
                ('deportes', models.ManyToManyField(blank=True, to='perfil.Deporte', verbose_name='Esportes')),
                ('estado_dientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='perfil.EstadoDientes', verbose_name='Estado Dentes')),
                ('idiomas', models.ManyToManyField(blank=True, to='perfil.Idioma', verbose_name='Idiomas')),
                ('instrumentos', models.ManyToManyField(blank=True, to='perfil.Instrumento', verbose_name='Instrumentos')),
                ('ojos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='perfil.Ojos', verbose_name='Olhos')),
                ('pelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='perfil.Pelo', verbose_name='Cabelo')),
                ('piel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='perfil.Piel', verbose_name='Pele')),
            ],
            options={
                'verbose_name_plural': 'Agenciados',
                'verbose_name': 'Agenciado',
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Agenciador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DireccionAgencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=60, null=True, verbose_name='Descripção')),
                ('barrio', models.CharField(blank=True, max_length=60, null=True, verbose_name='Barrio')),
                ('direccion', models.CharField(max_length=120, verbose_name='Endereço')),
                ('codigo_postal', models.CharField(blank=True, max_length=40, null=True, verbose_name='CEP')),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.Agencia', verbose_name='Agencia')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='direccion.Ciudad', verbose_name='Cidade')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.Region', verbose_name='Estado')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.Country', verbose_name='Pais')),
            ],
            options={
                'verbose_name_plural': 'Endereços da Agencia',
                'abstract': False,
                'verbose_name': 'Endereço da Agencia',
            },
        ),
        migrations.CreateModel(
            name='DireccionAgenciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=60, null=True, verbose_name='Descripção')),
                ('barrio', models.CharField(blank=True, max_length=60, null=True, verbose_name='Barrio')),
                ('direccion', models.CharField(max_length=120, verbose_name='Endereço')),
                ('codigo_postal', models.CharField(blank=True, max_length=40, null=True, verbose_name='CEP')),
                ('agenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.Agenciado', verbose_name='Agenciado')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='direccion.Ciudad', verbose_name='Cidade')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.Region', verbose_name='Estado')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.Country', verbose_name='Pais')),
            ],
            options={
                'verbose_name_plural': 'Endereços agenciados',
                'abstract': False,
                'verbose_name': 'Endereço agenciado',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadTrabajoAgenciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_desde', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día desde')),
                ('dia_hasta', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día hasta')),
                ('hora_desde', models.TimeField(blank=True, null=True, verbose_name='Hora desde')),
                ('hora_hasta', models.TimeField(blank=True, null=True, verbose_name='Hora hasta')),
                ('agenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.Agenciado')),
            ],
            options={
                'verbose_name_plural': 'Disponibilidades Trabajo',
                'abstract': False,
                'verbose_name': 'Disponibilidad Trabajo',
            },
        ),
        migrations.CreateModel(
            name='FotoAgenciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='agenciados/fotos/', validators=[iampacks.agencia.agencia.models.validate_image], verbose_name='Foto (tamaño < 1 MB)')),
                ('agenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.Agenciado')),
            ],
            options={
                'verbose_name_plural': 'Fotos agenciado',
                'verbose_name': 'Foto agenciado',
            },
        ),
        migrations.CreateModel(
            name='MailAgenciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripção')),
                ('agenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.Agenciado')),
            ],
            options={
                'verbose_name_plural': 'Mails Agenciado',
                'verbose_name': 'Mail Agenciado',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=60, verbose_name='Telefone')),
                ('agenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.Agenciado')),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='telefono.Compania', verbose_name='Compania')),
            ],
            options={
                'verbose_name_plural': 'Telefones agenciado',
                'abstract': False,
                'verbose_name': 'Telefone agenciado',
            },
        ),
        migrations.CreateModel(
            name='TelefonoAgencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=60, verbose_name='Telefone')),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.Agencia', verbose_name='Agencia')),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='telefono.Compania', verbose_name='Compania')),
            ],
            options={
                'verbose_name_plural': 'Telefones da Agencia',
                'abstract': False,
                'verbose_name': 'Telefone da Agencia',
            },
        ),
        migrations.CreateModel(
            name='TrabajoRealizadoAgenciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('fecha_desde', models.DateField(verbose_name='Fecha desde')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha hasta')),
                ('agenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.Agenciado')),
            ],
            options={
                'verbose_name_plural': 'Trabajos realizados',
                'abstract': False,
                'verbose_name': 'Trabajo realizado',
            },
        ),
        migrations.CreateModel(
            name='TrabajoVigenteAgenciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('fecha_vigencia', models.DateField(verbose_name='Fecha vigencia')),
                ('agenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.Agenciado')),
            ],
            options={
                'verbose_name_plural': 'Trabajos vigentes',
                'abstract': False,
                'verbose_name': 'Trabajo vigente',
            },
        ),
        migrations.CreateModel(
            name='VideoAgenciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, null=True, unique=True)),
                ('codigo_video', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('agenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.Agenciado')),
            ],
            options={
                'verbose_name_plural': 'Videos agenciado',
                'abstract': False,
                'verbose_name': 'Video agenciado',
            },
        ),
        migrations.AddField(
            model_name='agenciado',
            name='referente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencia.Agenciador'),
        ),
        migrations.AddField(
            model_name='agenciado',
            name='talle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='perfil.Talle', verbose_name='Manequim'),
        ),
        migrations.AddField(
            model_name='agenciado',
            name='talle_ropa_camisa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camisa', to='perfil.TalleRopa', verbose_name='Camisa'),
        ),
        migrations.AddField(
            model_name='agenciado',
            name='talle_ropa_pantalon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pantalon', to='perfil.TalleRopa', verbose_name='Calça'),
        ),
        migrations.AddField(
            model_name='agenciado',
            name='user',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
