# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenciado',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2016, 3, 6, 20, 42, 56, 763788, tzinfo=utc), verbose_name='Data de agenciamento'),
        ),
    ]
