# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0004_auto_20160306_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenciado',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de agenciamento'),
        ),
    ]
