# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='danza',
            name='descripcion_es',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='danza',
            name='descripcion_pt_br',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='deporte',
            name='descripcion_es',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='deporte',
            name='descripcion_pt_br',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='estadodientes',
            name='descripcion_es',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='estadodientes',
            name='descripcion_pt_br',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='idioma',
            name='descripcion_es',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='idioma',
            name='descripcion_pt_br',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='descripcion_es',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='descripcion_pt_br',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='ojos',
            name='descripcion_es',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='ojos',
            name='descripcion_pt_br',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='pelo',
            name='descripcion_es',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='pelo',
            name='descripcion_pt_br',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='piel',
            name='descripcion_es',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='piel',
            name='descripcion_pt_br',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='talle',
            name='descripcion_es',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='talle',
            name='descripcion_pt_br',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripção'),
        ),
        migrations.AddField(
            model_name='talleropa',
            name='descripcion_es',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='talleropa',
            name='descripcion_pt_br',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Descripción'),
        ),
    ]
