# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 20:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorol',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 6, 20, 44, 32, 550184), null=True, verbose_name='Data do evento'),
        ),
        migrations.AlterField(
            model_name='eventotrabajo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 6, 20, 44, 32, 550184), null=True, verbose_name='Data do evento'),
        ),
    ]
