# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 21:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0004_auto_20160306_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorol',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 6, 21, 2, 4, 193020), null=True, verbose_name='Data do evento'),
        ),
        migrations.AlterField(
            model_name='eventotrabajo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 6, 21, 2, 4, 193020), null=True, verbose_name='Data do evento'),
        ),
    ]
