# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0005_auto_20160306_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorol',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data do evento'),
        ),
        migrations.AlterField(
            model_name='eventotrabajo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data do evento'),
        ),
        migrations.AlterField(
            model_name='itemportfolio',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data ingreso'),
        ),
    ]
