# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 20:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencia', '0003_auto_20160306_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailInvalido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('fecha_deteccion', models.DateTimeField(default=datetime.datetime(2016, 3, 6, 20, 44, 32, 559979), verbose_name='Fecha de detección')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionCuentaAgenciadoExistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destinatario', models.EmailField(max_length=254, null=True, verbose_name='e-mail destinatario')),
                ('fecha_envio', models.DateTimeField(default=datetime.datetime(2016, 3, 6, 20, 44, 32, 559158), verbose_name='Fecha de envío')),
                ('agenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.Agenciado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
