# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notificacion', '0004_auto_20160306_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacioncuentaagenciadoexistente',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de envío'),
        ),
    ]
